logging:
  level:
    root: INFO
    com.boasaude: INFO
    io.netty.util.internal: INFO

server:
  port: 9998

spring:
  cloud:
    stream:
      binders:
        addressQueue:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                addresses: rabbit:5672
      bindings:
        solicitar-impressao-carteira-event:
          destination: solicitar-impressao-carteira-event
          content-type: application/json
          group: solicitarImpressao
          binder: addressQueue
          consumer:
            concurrency: 50
        solicitar-cobranca-segunda-via-carteira-event:
          destination: solicitar-cobranca-segunda-via-carteira-event
          content-type: text/plain
          group: solicitarCobranca
          binder: addressQueue
          consumer:
            concurrency: 50